before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -w
  - -X github.com/Ladicle/kubectl-check/cmd.version={{.Version}}
  - -X github.com/Ladicle/kubectl-check/cmd.commit={{.ShortCommit}}
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
archives:
- builds:
  - kubectl-check
  name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
  format: tar.gz
  files:
  - LICENSE
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
brews:
- name: kubectl-check
  tap:
    owner: Ladicle
    name: homebrew-brew
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  description: "Check Kubernetes resource"
  homepage: "https://github.com/Ladicle/kubectl-check"
