name: release
on:
  push:
    tags:
    - '*'
env:
  GO: 1.14.x
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO }}
    - name: Docker Login
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login ghcr.io --username Ladicle --password-stdin
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    - name: Clear
      if: always() && startsWith(github.ref, 'refs/tags/')
      run: |
        rm -f ${HOME}/.docker/config.json
